###
// Muestra la pagina principal
GET http://localhost:8080
###
// Muestra todas las notas.
GET http://localhost:8080/api/notes
###
// // Busca la nota por id.
GET http://localhost:8080/api/notes/65089e26e54ad8f2481e3dac
###
// Añade una nota.
POST http://localhost:8080/api/notes
Content-Type: application/json

{
    "content": "Elimina esta nota",
    "important": true
}
###
// Elimina una nota.
DELETE http://localhost:8080/api/notes/6508cc13605dce1b0027ba21
###
// Actualiza una nota.
PUT http://localhost:8080/api/notes/65089e26e54ad8f2481e3dac
Content-Type: application/json

{
    "content": "Dunder mifflin paper company",
    "important": true
}
